version: '3'
services:
  suggestionbot:
    container_name: suggestionbot
    restart: always
    build: .
    environment:
      - NODE_ENV=production
      - TOKEN=<token>
    volumes:
      - ./suggestionbot.sqlite:/usr/app/suggestionbot.sqlite